// frontend-react/src/components/partials/Login.jsx
import { useState } from 'react'
import '../../index.css'
import fastAPIconn from '../../auth/authenticate';
import { Form } from 'react-router-dom';
import { useSelector } from 'react-redux';

function LoginComp() {
    function handleSubmit(e) {
        // Prevent the browser from reloading the page
        e.preventDefault();
    
        const form = e.target;
        const formData = new FormData(form);
        let params = {
            username: formData.get("username"),
            password: formData.get("password")
        }

        fastAPIconn('/api/user/login', 'login', params)
        .then((data) => {
            if (data.detail) {
                alert(data.detail)
            } else {
                console.log(data.access_token)
            }
        })
    }

    return (
        <div className="text-white py-5 px-8 flex flex-col bg-zinc-700 min-w-[420px]">
            <h1 className="p-2 text-xl text-center font-bold">Login Page</h1>
            <Form method="POST" onSubmit={handleSubmit} className="grid grid-col justify-items-stretch gap-5 my-2">
                <label className="grid grid-row gap-2 text-left">
                    <b>Username</b>
                    <input className="bg-zinc-800 p-2"
                        name="username"
                        type="text"
                        required
                    />
                </label>
                <label className="grid grid-row gap-2 text-left">
                    <b>비밀번호</b>
                    <input className="bg-zinc-800 p-2"
                        name="password"
                        type="password"
                        required
                    />
                </label>
                <button type="submit" className="bg-zinc-600 px-5 py-2 flex-shrink my-2.5">로그인</button>
            </Form>
            <p className='py-2.5 mt-2.5'>
                아직 회원이 아니라면? <a href='/signup'>회원가입</a>
            </p>
        </div>
    );
}

export default LoginComp;

// front-ui-svelte/src/routes/login/+page.svelte
<script>

</script>

<div class="flex justify-center">
<div class="text-white rounded-lg py-8 px-10 flex flex-col bg-zinc-700 justify-self-center self-center min-w-[420px]">
    <h1 class="p-2.5 text-xl text-center font-bold">로그인</h1>
    <form method="POST" class="grid grid-col align-center gap-2.5 my-2.5">
		<label class="grid grid-row gap-2 ">
			<b>Username</b>
			<input class="bg-zinc-800 p-2 rounded-lg"
				name="username"
				autocomplete="off"
			/>
		</label>
        <label class="grid grid-row gap-2">
			<b>비밀번호</b>
			<input class="bg-zinc-800 p-2 rounded-lg"
				name="password"
				type="password"
			/>
		</label>
        <button type="submit" class="bg-zinc-600 rounded-lg px-5 py-2 flex-shrink my-2.5">로그인</button>
	</form>
</div>
</div>
